# Generated by Django 5.1.2 on 2025-08-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_content_type_ticket_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticketreassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
