# Generated by Django 5.1.2 on 2025-08-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketlog_updated_at_ticketreassignment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
