# Generated by Django 4.2.23 on 2025-09-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_object_id'),
        ('tickets', '0004_question_reassignmentanswer_ticketanswer'),
    ]

    operations = [
    ]
