# Generated by Django 5.1.2 on 2025-09-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_object_id'),
        ('tickets', '0004_question_reassignmentanswer_ticketanswer'),
    ]

    operations = [
    ]
