# Generated by Django 5.1.2 on 2025-09-08 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_merge_20250904_0934'),
        ('tickets', '0005_merge_20250904_1010'),
    ]

    operations = [
    ]
