# Generated by Django 5.1.2 on 2025-09-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_merge_20250908_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='object_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='models_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='models_name',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=20),
        ),
    ]
