# Generated by Django 5.1.2 on 2025-09-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticket_content_type_remove_ticket_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='models_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='models_name',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened')], default='open', max_length=255),
        ),
    ]
