# Generated by Django 5.1.2 on 2025-09-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketreassignment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
