# Generated by Django 5.1.2 on 2025-09-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_ticketlog_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='models_object',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
