# Generated by Django 4.2.23 on 2025-09-19 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0013_ngoauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Status History',
                'verbose_name_plural': 'Ticket Status Histories',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket'], name='tickets_tic_ticket__8ee7d2_idx')],
            },
        ),
    ]
