# Generated by Django 4.2.23 on 2025-09-22 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticketstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
