# Generated by Django 4.2.23 on 2025-09-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_ticket_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='ticketReassignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reassignment_logs', to='tickets.ticketreassignment'),
        ),
    ]
