# Generated by Django 4.2.23 on 2025-09-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_ticketlog_ticketreassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreassignment',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
