# Generated by Django 4.2.23 on 2025-10-07 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0018_category_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketQuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_answer', models.TextField()),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticketanswer')),
            ],
        ),
    ]
