# Generated by Django 4.2.23 on 2025-10-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_ticketquestionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketanswer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticketanswer',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
