# Generated by Django 4.2.23 on 2025-10-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_ticketanswer_is_active_ticketanswer_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketquestionhistory',
            name='old_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
