# Generated by Django 4.2.23 on 2025-10-14 07:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0022_ticket_request_type_fileupload'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticketanswer',
            unique_together={('ticket', 'question', 'answered_by')},
        ),
    ]
