# Generated by Django 4.2.23 on 2025-10-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_alter_ticketanswer_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='reassigne',
            new_name='reassignment',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='models_name',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed')], default='open', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='new_status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed')], max_length=20, null=True),
        ),
    ]
