# Generated by Django 4.2.23 on 2025-10-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_rename_reassigne_fileupload_reassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='log',
            field=models.ForeignKey(blank=True, help_text='Link this file upload to a specific ticket log entry', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='tickets.ticketlog'),
        ),
    ]
