# Generated by Django 5.1.2 on 2025-10-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_fileupload_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationsOther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcn', models.CharField(blank=True, db_comment='registration number', max_length=10, null=True)),
                ('registration_application_id', models.CharField(blank=True, db_comment='application Id', max_length=27, null=True)),
                ('section_file_number', models.CharField(blank=True, max_length=19, null=True)),
                ('form_submission_date', models.CharField(blank=True, db_comment='application submission date', max_length=50, null=True)),
                ('darpan_id', models.CharField(blank=True, max_length=17, null=True)),
                ('association_name', models.CharField(blank=True, db_comment='ngo Name\t', max_length=100, null=True)),
                ('association_address', models.TextField(blank=True, null=True)),
                ('association_state', models.CharField(blank=True, max_length=27, null=True)),
                ('association_district', models.CharField(blank=True, max_length=100, null=True)),
                ('association_official_telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('association_email', models.CharField(blank=True, max_length=52, null=True)),
                ('association_official_website', models.CharField(blank=True, max_length=100, null=True)),
                ('association_chief_functionary_phone_number', models.CharField(blank=True, max_length=42, null=True)),
                ('association_chief_functionary_mobile_number', models.CharField(blank=True, max_length=43, null=True)),
                ('act_registration_name', models.CharField(blank=True, max_length=148, null=True)),
                ('act_registration_number', models.CharField(blank=True, max_length=52, null=True)),
                ('date_of_act_registration', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_act_registration', models.CharField(blank=True, max_length=149, null=True)),
                ('association_pan', models.CharField(blank=True, max_length=11, null=True)),
                ('association_nature', models.CharField(blank=True, max_length=46, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=44, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_email', models.CharField(blank=True, max_length=56, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=32, null=True)),
                ('association_status', models.CharField(blank=True, max_length=50, null=True)),
                ('cancel_suspended_date', models.CharField(blank=True, max_length=26, null=True)),
                ('cancelled_suspended_remark', models.CharField(blank=True, max_length=651, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=19, null=True)),
                ('registration_certificate_location', models.CharField(blank=True, max_length=33, null=True)),
                ('registration_applications_documents_location', models.CharField(blank=True, max_length=44, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
