# Generated by Django 5.1.2 on 2025-11-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_created_by'),
        ('tickets', '0026_registrationsother'),
    ]

    operations = [
    ]
