# Generated by Django 5.1.2 on 2025-11-05 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_otherservicesdocumentslink_registrations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketApplicationDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='ticket_application_docs/%Y/%m/%d/')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('other_services_documents_link', models.ForeignKey(db_column='other_services_documents_link', on_delete=django.db.models.deletion.CASCADE, related_name='application_docs', to='tickets.otherservicesdocumentslink')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_application_docs_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ticket_application_doc',
                'managed': True,
            },
        ),
    ]
