# Generated by Django 5.1.2 on 2025-11-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_create_ticket_application_doc_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketapplicationdoc',
            name='uploaded_by',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
