# Generated by Django 5.1.2 on 2025-11-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_alter_ticketapplicationdoc_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketapplicationdoc',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='ticketapplicationdoc',
            name='uploaded_by_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
