# Generated by Django 5.1.2 on 2025-11-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_remove_ticketapplicationdoc_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rcn',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
