# Generated by Django 5.1.2 on 2025-11-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_ticket_file_no_ticket_rcn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketapplicationdoc',
            name='ticket_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
