# Generated by Django 5.1.2 on 2025-11-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_ticketapplicationdoc_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassignmentanswer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reassignmentanswer',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketanswer',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='models_name',
            field=models.CharField(choices=[('ngo', 'NGO'), ('str', 'STR'), ('spyder', 'Sypder'), ('cms', 'CMS')], default='ngo', max_length=255),
        ),
    ]
