# Generated by Django 5.1.2 on 2025-11-18 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0036_reassignmentanswer_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketlog',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_logs_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='message',
            field=models.TextField(blank=True, default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='ticketanswer',
            unique_together={('ticket', 'question', 'answered_by', 'version')},
        ),
    ]
