# Generated by Django 5.1.2 on 2025-11-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0037_ticketlog_to_user_alter_ticketlog_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='report_dateils',
            field=models.TextField(blank=True, null=True),
        ),
    ]
