# Generated by Django 5.1.2 on 2025-11-19 07:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_remove_fileupload_report_dateils_reportsummary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reassignmentanswer',
            unique_together={('reassignment', 'question', 'answered_by')},
        ),
    ]
