# Generated by Django 5.1.2 on 2025-12-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0040_alter_reassignmentanswer_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMembersData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fcra_registration_no', models.CharField(blank=True, max_length=50, null=True)),
                ('association_name', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=150, null=True)),
                ('member_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_husband_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('post_in_association', models.CharField(blank=True, max_length=200, null=True)),
                ('relationship_with_other_member', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'committee_members_data',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('submitted', 'Submitted')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='new_status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('submitted', 'Submitted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('assigned', 'Assigned'), ('closed', 'Closed'), ('reopened', 'Reopened'), ('submitted', 'Submitted')], max_length=20, null=True),
        ),
    ]
