# Generated by Django 5.1.2 on 2026-01-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_committeemembersdata_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilizationBnkDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fcra_registration_no', models.CharField(max_length=191)),
                ('application_id', models.CharField(max_length=191)),
                ('association_name', models.CharField(max_length=191)),
                ('registration_date', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(max_length=191)),
                ('bank_address', models.TextField()),
                ('account_no', models.CharField(max_length=191)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilization_bnk_details',
                'managed': False,
            },
        ),
    ]
