# Generated by Django 5.1.2 on 2026-01-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_utilizationbnkdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(blank=True, max_length=21, null=True)),
                ('whether_indian_origin', models.BooleanField(blank=True, null=True)),
                ('member_name', models.CharField(blank=True, max_length=56, null=True)),
                ('father_husband_name', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('post_in_association', models.CharField(blank=True, max_length=49, null=True)),
                ('relationship_with_other_member', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('address_foreign_country', models.TextField(blank=True, null=True)),
                ('application_id', models.CharField(blank=True, max_length=17, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('date_place_of_birth', models.CharField(blank=True, max_length=150, null=True)),
                ('date_from_residing_india', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_committee_member_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrationApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_application_id', models.CharField(blank=True, max_length=20, null=True)),
                ('section_file_number', models.CharField(blank=True, max_length=20, null=True)),
                ('form_submission_date', models.CharField(blank=True, max_length=20, null=True)),
                ('darpan_id', models.CharField(blank=True, max_length=20, null=True)),
                ('association_name', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_date', models.CharField(blank=True, max_length=20, null=True)),
                ('association_address', models.CharField(blank=True, max_length=255, null=True)),
                ('association_state', models.CharField(blank=True, max_length=50, null=True)),
                ('association_district', models.CharField(blank=True, max_length=50, null=True)),
                ('association_official_telephone', models.TextField(blank=True, null=True)),
                ('email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('association_official_website', models.CharField(blank=True, max_length=100, null=True)),
                ('association_chief_functionary_phone_number', models.TextField(blank=True, null=True)),
                ('association_chief_functionary_mobile_number', models.TextField(blank=True, null=True)),
                ('act_registration_name', models.TextField(blank=True, null=True)),
                ('act_registration_number', models.TextField(blank=True, null=True)),
                ('date_of_act_registration', models.TextField(blank=True, null=True)),
                ('place_of_act_registration', models.TextField(blank=True, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=15, null=True)),
                ('nature_of_association', models.TextField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_address', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_email_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc_code', models.TextField(blank=True, null=True)),
                ('account_number', models.TextField(blank=True, null=True)),
                ('association_status', models.TextField(blank=True, null=True)),
                ('registration_applications_documents_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application_details',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='otherservicesdocumentslink_logs',
            options={'managed': False},
        ),
    ]
