# Generated by Django 5.1.2 on 2026-01-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_committeedetails_registrationapplications_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='otherservicesdocumentslink_logs',
            table='other_services_documents_linkraw',
        ),
    ]
