# Generated by Django 5.1.2 on 2026-02-23 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_alter_otherservicesdocumentslink_logs_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSyncLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=100)),
                ('table_name', models.CharField(db_index=True, max_length=100)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inserted', models.BigIntegerField(default=0)),
                ('updated', models.BigIntegerField(default=0)),
                ('skipped', models.BigIntegerField(default=0)),
                ('last_sync_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_sync_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketMemberRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('NGO', 'NGO'), ('OFFICE_BEARER', 'OFFICE_BEARER')], db_index=True, max_length=30)),
                ('member_name', models.CharField(blank=True, max_length=200, null=True)),
                ('father_husband_name', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('post_in_association', models.CharField(blank=True, max_length=200, null=True)),
                ('relationship_with_other_member', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=50, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_rows', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_member_row',
                'indexes': [models.Index(fields=['ticket', 'section_type'], name='ticket_memb_ticket__46b019_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketSectionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('USER_SECTION', 'User Section (NGO Query)'), ('OFFICE_BEARER', 'Office Bearer Query')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_section_meta',
                'unique_together': {('ticket', 'section_type')},
            },
        ),
    ]
