# Generated by Django 5.1.2 on 2026-02-23 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0046_assignuserscategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignuserscategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignuserscategory',
            name='member_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='tickets.ticketmemberrow'),
        ),
        migrations.AddField(
            model_name='assignuserscategory',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='assign_user_categories', to='tickets.question'),
        ),
        migrations.AddField(
            model_name='assignuserscategory',
            name='section_type',
            field=models.CharField(choices=[('NGO', 'NGO'), ('OFFICE_BEARER', 'OFFICE_BEARER')], db_index=True, default='NGO', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='assignuserscategory',
            constraint=models.UniqueConstraint(fields=('ticket', 'section_type', 'member_row', 'user', 'category'), name='uniq_ticket_section_member_user_category'),
        ),
    ]
