# Generated by Django 5.1.2 on 2026-02-24 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_alter_assignuserscategory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='ticket',
        #     name='mha_file_no',
        #     field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        # ),
        migrations.CreateModel(
            name='TicketAdverseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_adverse', models.BooleanField(default=False)),
                ('adverse_option', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_adverse_created', to=settings.AUTH_USER_MODEL)),
                ('status_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_rows', to='tickets.ticketstatushistory')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_history', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_adverse_history',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket'], name='ticket_adve_ticket__6ff65e_idx'), models.Index(fields=['created_at'], name='ticket_adve_created_56a4d6_idx')],
            },
        ),
    ]
