# Generated by Django 5.1.2 on 2026-02-24 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0048_ticket_mha_file_no_ticketadversehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdverseReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketadversehistory',
            name='adverse_option',
        ),
        # migrations.AddField(
        #     model_name='ticket',
        #     name='mha_file_no',
        #     field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        # ),
        migrations.AddField(
            model_name='ticketadversehistory',
            name='adverse_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_adverse_history', to='tickets.adversereason'),
        ),
    ]
