# Generated by Django 5.1.2 on 2026-02-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_adversereason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmemberrow',
            name='member_data_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
