# Generated by Django 5.1.2 on 2026-02-25 08:34

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0050_ticketmemberrow_member_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('kind', models.CharField(max_length=10)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('rows', models.JSONField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'import_sessions',
                'managed': False,
            },
        ),
    ]
