# Generated by Django 5.1.2 on 2026-03-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_importsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mha_file_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
