# Generated by Django 5.1.2 on 2026-02-25 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_ticket_mha_file_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketActionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_key', models.CharField(db_index=True, max_length=100)),
                ('is_success', models.BooleanField(default=False)),
                ('status_text', models.CharField(blank=True, max_length=255, null=True)),
                ('error_text', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_traces', to='tickets.ticket')),
            ],
            options={
                'db_table': 'ticket_action_trace',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['ticket', 'action_key'], name='ticket_acti_ticket__90069c_idx')],
            },
        ),
    ]
