# Generated by Django 5.1.2 on 2026-03-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_importsession'),
        ('tickets', '0052_ticketactiontrace'),
    ]

    operations = [
    ]
