# Generated by Django 4.2.23 on 2026-03-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0052_ticket_mha_file_no'),
        ('tickets', '0053_merge_0051_importsession_0052_ticketactiontrace'),
    ]

    operations = [
    ]
