# Generated by Django 5.1.2 on 2026-03-25 06:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0057_ticket_signater'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticketactiontrace',
            name='ticket_acti_ticket__90069c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='reassignmentanswer',
            unique_together={('reassignment', 'is_active', 'is_final', 'question', 'answered_by')},
        ),
        migrations.AlterUniqueTogether(
            name='ticketanswer',
            unique_together={('ticket', 'question', 'is_active', 'is_final', 'answered_by', 'version')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by'], name='tickets_tic_created_d1df98_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['models_name'], name='tickets_tic_models__7f7c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['models_id'], name='tickets_tic_models__610d11_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketactiontrace',
            index=models.Index(fields=['ticket', 'is_success', 'action_key'], name='ticket_acti_ticket__cd5ced_idx'),
        ),
    ]
